### ISSUE TITLE
Import of any type of content fails - stack trace is suppressed?

### ISSUE THREAD

**Issue by etherealite** [simjanos-dev/LinguaCafe#227] opened 2024-04-28 17:14 UTC
Hi, 

I'd like say that I'm very excited about this project and used it to import some Japanese subtitles with success. It really hits the right notes compared to its competitors, it really is love at first site for me. So it's a little bitter sweet to have things go south when I was pretty much on the edge of my seat, head over heals pumped on how cool this thing is.

I'm not sure how to report which version I'm running since the compose file simply pulls the latest images. For the record I'll simply post the results of `docker compose images` for you bellow:

```
CONTAINER                   REPOSITORY                                       TAG                 IMAGE ID            SIZE
linguacafe-database         mysql                                            8.0                 a53272402242        175MB
linguacafe-python-service   ghcr.io/simjanos-dev/linguacafe-python-service   latest              0e2b8e1acd98        700MB
linguacafe-webserver        ghcr.io/simjanos-dev/linguacafe-webserver        latest              fdbb35d1576c        242MB
```

Suddenly I went to import some new content after happily reading some of the things I had imported previously. When I did so, I was met with an error. The same error occurs no matter what type of content I'm importing, any length, any type. A red flash message pops up saying  'An error has occurred while importing your text.' I can't glean much more than this, as when I tried to investigate the Laravel stack trace, I found that it's obscured by a try catch block. It's a catch all that can be seen on this line of the [ImportController](https://github.com/simjanos-dev/LinguaCafe/blob/da154c3e0c76b92416b38b4dde2218078e1d9ea2/app/Http/Controllers/ImportController.php#L75) class.

I'd really rather know why something is blowing up rather than have the stack trace suppressed. I'd be able to provide better feedback than just `undefined array key 0` from who knows where.

## Post Request
POST http://localhost:9191/import 

### form encoded data:
```
importType: plain-text
importText: DJマキコ：みなさん、こんばんは。ＤＪマキコです。

DJマキコ：みなさん、こんばんは。ＤＪマキコです。

: 今日のゲストは、マナーの達人の米田ハツさんです。

米田ハツ：(咳払い）宜しくお願い致します。

DJマキコ：今日は、中国からの留学生、金さんからの質問です。

: 「友達に遊びに行こうと誘われたのですが、どうやって断ればいいでしょうか。」

米田ハツ：日本人は、基本的に直接はっきりと「いいえ」と言わないことが多いです。

: 相手に気づいてもらえるように、話し方に気をつけましょう。

: あと、理由を言えば、完璧ですね。

DJマキコ：なるほど。例えば、

: 「その日はちょっと･･･。次の日にテストがあるんですよ。」とかですか？

米田ハツ：そうです。あと、相手にしっかりと謝ることですね。

: せっかく相手が誘ってくれたのですから。
textProcessingMethod: detailed
bookId: -1
bookName: daggah
chapterName: ggads
maximumCharactersPerChapter: 1500
```

## Stack Trace
```JSON
{
    "message": "Undefined array key 0",
    "exception": "Symfony\\Component\\HttpKernel\\Exception\\HttpException",
    "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php",
    "line": 1132,
    "trace": [
        {
            "file": "/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php",
            "line": 44,
            "function": "abort",
            "class": "Illuminate\\Foundation\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/app/Http/Controllers/ImportController.php",
            "line": 81,
            "function": "abort"
        },
```

**Comment by simjanos-dev** [comment] 2024-04-28 17:24
Hi!

> I'd like say that I'm very excited about this project and used it to import some Japanese subtitles with success.

I'm glad you like it! 

Based on the stack trace http error message, I think it has to do something with the python server that supposed to parse the text. 

You can see the version number on the bottom of the home page. I have an idea what could cause this. Did you by any chance update from v0.10 to higher? 

In v0.11 we made Japanese an installable language, and your selected language supposed to reset to Spanish. If by some error it didn't reset, and you did update, you maybe just have to install it on the Admin -> Languages page. If something else is the problem, you can still try to uninstall and install Japanese again.

Can you please copy the python server's docker log?

**Comment by etherealite** [comment] 2024-04-28 17:39
Wow, thank you so much for the insta response. Yeah, I'm super pumped about Lingua Cafe.

Yeah it was a fresh install on what was probably v0.11.1 as I installed it ~30 hours ago. I did install Japanese as an installable language when I set things up and imported the dictionaries. I pulled in the new v0.11.2 docker images hoping it would fix the problem, but nothing changed.

Here is some the python containers logs after trying to import a couple different pieces of content that trigger the error:
```
2024-04-28 09:32:46 Bottle v0.12.25 server starting up (using WSGIRefServer())...
2024-04-28 09:32:46 Listening on http://0.0.0.0:8678/
2024-04-28 09:32:46 Hit Ctrl-C to quit.
2024-04-28 09:32:46 
2024-04-28 09:33:15 172.20.0.4 - - [28/Apr/2024 16:33:15] "POST /tokenizer/get-subtitle-file-content HTTP/1.1" 200 23259
2024-04-28 09:33:21 <frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
2024-04-28 09:33:29 172.20.0.4 - - [28/Apr/2024 16:33:29] "POST /tokenizer/import-subtitles HTTP/1.1" 200 221747
2024-04-28 09:35:30 172.20.0.4 - - [28/Apr/2024 16:35:30] "POST /tokenizer/import-subtitles HTTP/1.1" 200 221747
2024-04-28 09:35:39 172.20.0.4 - - [28/Apr/2024 16:35:39] "POST /tokenizer/import-subtitles HTTP/1.1" 200 221747
2024-04-28 09:40:39 172.20.0.4 - - [28/Apr/2024 16:40:39] "GET /models/list HTTP/1.1" 200 12
2024-04-28 09:44:34 172.20.0.4 - - [28/Apr/2024 16:44:34] "POST /tokenizer/import-text HTTP/1.1" 200 28479
2024-04-28 09:45:10 172.20.0.4 - - [28/Apr/2024 16:45:10] "POST /tokenizer/import-text HTTP/1.1" 200 28479
2024-04-28 10:31:09 172.20.0.4 - - [28/Apr/2024 17:31:09] "GET /models/list HTTP/1.1" 200 12
2024-04-28 10:31:16 172.20.0.4 - - [28/Apr/2024 17:31:16] "GET /models/list HTTP/1.1" 200 12
2024-04-28 10:31:25 172.20.0.4 - - [28/Apr/2024 17:31:25] "GET /models/list HTTP/1.1" 200 12
2024-04-28 10:36:21 172.20.0.4 - - [28/Apr/2024 17:36:21] "POST /tokenizer/get-subtitle-file-content HTTP/1.1" 200 23259
2024-04-28 10:36:36 172.20.0.4 - - [28/Apr/2024 17:36:36] "POST /tokenizer/import-subtitles HTTP/1.1" 200 221747
```

**Comment by simjanos-dev** [comment] 2024-04-28 18:02
That is super weird, never had similar issues. Can you please try to import something in an other language? If yes, can you try uninstalling all your languages, and install Japanese again? It seems like the python server is working, so I don't think reinstalling would fix it but... I don't have many ideas.

Did anything changed with the docker or the folders/files before it stopped working?

Do you by any chance have the exact text that you imported when it broke the first time?

**Comment by simjanos-dev** [comment] 2024-04-28 19:16
I've tried importing something in an uninstalled language, but the python function threw an error as it should. I don't think re-installing the language would help.

The error is an HttpException, it is in the `app/Models/TextBlock.php` file in `tokenizeRawText` function. The only problem so far with the HTTP request was if it could not reach the python server, but based on the python logs the request was received, and the python server is functioning as intended.

I'm a bit lost, because I have no way to reproduce this issue.

**Comment by etherealite** [comment] 2024-04-28 19:45
> Can you please try to import something in an other language? If it works, can you try uninstalling all your languages, and install Japanese again?

Will do.

> Did anything changed with the docker or the folders/files before it stopped working?

Not that I am aware of, I never once even stopped the containers and I didn't move any of the volume mounts.

> Do you by any chance have the exact text that you imported when it broke the first time?

I did do this. I tried numerous times to with the original working text using all of text, text file, subtitle import types.

> Is there maybe a more detailed error message in `linguacafe/storage/logs/laravel.log?`

Not really, just the normal grumbling about the DB server not being reachable when bringing up the docker compose stack.
```
[2024-04-28 21:30:48] local.ERROR: SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = linguacafe and table_name = migrations and table_type = 'BASE TABLE') {"exception":"[object] (Illuminate\\Database\\QueryException(code: 2002): SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = linguacafe and table_name = migrations and table_type = 'BASE TABLE') at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(784): Illuminate\\Database\\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
...
```

I can write files to the volume mounts just fine if I shell into the PHP docker container. I can delete the session file and Laravel is able to recreate them so apache can write to them as well.

I'll dig into things a bit further tomorrow and try and see what's going on with `app/Models/TextBlock.php` and the like.

**Comment by simjanos-dev** [comment] 2024-04-28 19:55
> I'll dig into things a bit further tomorrow and try and see what's going on with app/Models/TextBlock.php and the like.

Thank you, I'll try to help if I can!

Sorry that it stopped working, hope we can find out what's wrong.

**Comment by etherealite** [comment] 2024-04-29 08:07
> Can you please try to import something in an other language? If it works, can you try uninstalling all your languages, and install Japanese again?

I was able to import content using Spanish just fine.

When attempting to uninstall all languages, I experienced an error flash message in the browser. I went to open up the browser dev tools to get you some trace info, but when I hit the uninstall button again it mysteriously worked without errors.

Despite uninstalling all languages and reinstalling Japanese, the same issue is persisting.

> Do you by any chance have the exact text that you imported when it broke the first time?

Here is a gist with the [content file](https://gist.github.com/etherealite/e348f6f2f808e17fae70d595dbded408) and filename that broke everything: 


One thing I can say is that installing the languages seems to kick off Windows Defender if you're using Docker Desktop with volume mounts going directly to windows instead of inside a WSL instance. I found that the laravel.log file was read only from inside the the container. Fixed it so now I can see stack traces starting to show up.

**Comment by simjanos-dev** [comment] 2024-04-29 08:32
> Here is a gist with the [content file](https://gist.github.com/etherealite/e348f6f2f808e17fae70d595dbded408) and filename that broke everything

I've asked for this, because I wanted to test that there's maybe a bug in linguacafe, that corrupts the database. But I could import this without issues.

> When attempting to uninstall all languages, I experienced an error flash message in the browser. I went to open up the browser dev tools to get you some trace info, but when I hit the uninstall button again it mysteriously worked without errors.

We had similar issues before release, but thought it was fixed. I'll test it further. 

> One thing I can say is that installing the languages seems to kick off Windows Defender if you're using Docker Desktop with volume mounts going directly to windows instead of inside a WSL instance. 

I only tested it using it directly on windows without WSL.

If you are running on WSL, could you please test if the problem is with permissions? I don't think so but worth a quick try running this command from the linguacafe directory: `chmod -R 777 ./`. Japanese text parser models are stored in the `linguacafe/storage/app/model` directory, so it is possible that's what causes the issue. The 200 return code from the python logs indicate that it is working, because if a language model is missing, it would throw a 500 error. But maybe it is possible that due to permissions it is partially not working and returns 200 anyways.

If you install an other installable language, and that does not work either, that could confirm that the problem is with the installed models/server/setup.

If you are okay with it, I can help you change your password, export your database and I can check if it works for me. If it does not, it would confirm that the problem is either with the code, or the database is corrupted for some reason(which would still be due to code, because this should not happen).

@sergiolaverde0 

Sorry for tagging you in so many things. Any thoughts on WSL that could cause an issue?

**Comment by etherealite** [comment] 2024-04-29 08:34
I found it, somehow a phrase made it into the DB with no associated words.

Feast your eyes on this:
```PHP
> Phrase::where('user_id', 1)->where('language', 'japanese')->get();
= Illuminate\Database\Eloquent\Collection {#6134
    all: [
      App\Models\Phrase {#6948
        id: 4,
        user_id: 1,
        language: "japanese",
        words: "["\u8cac\u4efb","\u611f"]",
        reading: "せきにんかん",
        translation: "sense of responsibility",
        stage: 0,
        created_at: "2024-04-28 11:57:06",
        updated_at: "2024-04-28 11:57:06",
        words_searchable: "責任感",
        added_to_srs: null,
        next_review: null,
        relearning: 0,
        lookup_count: 0,
        read_count: 0,
      },
      App\Models\Phrase {#7103
        id: 5,
        user_id: 1,
        language: "japanese",
        words: "[]",
        reading: "さいごまでやります",
        translation: "Do it to the end (finish it)",
        stage: 0,
        created_at: "2024-04-28 11:58:22",
        updated_at: "2024-04-28 11:58:22",
        words_searchable: "",
        added_to_srs: null,
        next_review: null,
        relearning: 0,
        lookup_count: 0,
        read_count: 0,
      },
    ],
  }
  ```
After doing `Phrase::where('id', 5)->delete();` I'm back in business, everything is working again.

Then, after doing a little bit of this:
```PHP
        } catch (\Exception $e) {
            // delete temp file
            if (isset($importFile)) {
                $this->tempFileService->deleteTempFile($fileName);
            }

            // abort(500, $e->getMessage());
            throw $e;
        }
```






 Here is the stack trace:

```JSON
{
    "message": "Undefined array key 0",
    "exception": "ErrorException",
    "file": "/var/www/html/app/Models/TextBlock.php",
    "line": 408,
    "trace": [
        {
            "file": "/var/www/html/app/Models/TextBlock.php",
            "line": 408,
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/var/www/html/app/Models/TextBlock.php",
            "line": 379,
            "function": "updatePhraseIds",
            "class": "App\\Models\\TextBlock",
            "type": "->"
        },
        {
            "file": "/var/www/html/app/Services/ImportService.php",
            "line": 146,
            "function": "updateAllPhraseIds",
            "class": "App\\Models\\TextBlock",
            "type": "->"
        },
        {
            "file": "/var/www/html/app/Services/ImportService.php",
            "line": 89,
            "function": "importChunks",
            "class": "App\\Services\\ImportService",
            "type": "->"
        },
```

**Comment by simjanos-dev** [comment] 2024-04-29 08:40
I see what's the problem.

```
      App\Models\Phrase {#7103
        id: 5,
        user_id: 1,
        language: "japanese",
        words: "[]", // <----------------------------------- This one here
        reading: "さいごまでやります",
        translation: "Do it to the end (finish it)",
        stage: 0,
        created_at: "2024-04-28 11:58:22",
        updated_at: "2024-04-28 11:58:22",
        words_searchable: "",
        added_to_srs: null,
        next_review: null,
        relearning: 0,
        lookup_count: 0,
        read_count: 0,
      },

```

Somehow there was a phrase in the database that has 0 words in it. I am not sure how that happened, had no feedback about this problem before. But just to be safe I'll add check to prevent this.


Please do not use it yet, it is important! There can still be problem with it. I don't know how much content do you have imported. But if it's possible, please go to each book, each chapter, click on the three dots, edit chapter, and save it. Currently you cannot edit/save subtitles, so please delete subtitle chapters, and import them again. 

I'm still typing, but sent this comment so you can see it earlier...

**Comment by etherealite** [comment] 2024-04-29 09:21
I only had 2 chapters of content imported in total, so pretty much zero loss there. I have deleted the book containing them as well. 

The whole subtitle file that I imported can be seen in a gist [here](https://gist.github.com/etherealite/e348f6f2f808e17fae70d595dbded408) and the line that causes it is 

```
00:07:31,460 --> 00:07:35,890
責任、責任感(responsibility)

90
00:07:35,890 --> 00:07:40,890
だから「私がこれを最後までやります」

91
00:07:40,890 --> 00:07:43,510
「私が全部最後までやります」っていう

92
00:07:43,510 --> 00:07:49,320
そういう責任を持ってできるタイプ。

93
00:07:49,320 --> 00:07:55,640
で、心配症。「心配症」は心配する性格ね。
```

Seen in context of the gist here on line [365](https://gist.github.com/etherealite/e348f6f2f808e17fae70d595dbded408#file-416-blood-type-2j_pzpliise-ja-srt-L365). 


I've tried to recreate the broken phrase again but I can't seem to make it happen. 

The only thing I remember is that originally at the time, I created the phrase '最後までやります' and noticed something odd. The phrase is repeated in the subtitle content between 90 and 91, but the repeated instance of the phrase was not highlighted in the reader. I figured it was just some type of minor bug so I selected the second occurrence of the phrase and created it again.

![image](https://github.com/simjanos-dev/LinguaCafe/assets/838780/0e4b76e2-d59d-44b8-9c28-5567685d7477)

Please note that this was on version 11.1 so things look a little different compared to what's in this screenshot that is from 11.2.

**Comment by sergiolaverde0** [comment] 2024-04-29 12:46
> I'm not sure how to report which version I'm running since the compose file simply pulls the latest images

The IDs match those of v11.2, for the record.

> Sorry for tagging you in so many things

It's fine, it is good to stay informed of things happening with the project.

I think this happened to me once, with Korean, in the dozens of import cycles when testing the extra language install. It is certainly not reproducible and I don't think it depends on anything very specific, so best we can do is introduce a sanity check to catch it on time.

OP has also made a good point on logging too, and with `logrotate` or an appropriate middleware we could be more clear on the nature of errors without taking up too much storage.

It is so satisfying when the user reporting is this savvy.

**Comment by etherealite** [comment] 2024-04-29 15:04
I'm glad to by chance, to have a some of working experience with the tech stack in play here.

While I still have your attention, here is a quick feature request regarding logging and errors.

First and foremost I would ask that errors that are exceptional (unexpected) be fully logged before they get swept away `abort()`

Since you're already using docker container logging with the python service, I think having Laravel provide the same would be beneficial. I would be able to see error messages on the containers log and pipe it to some type of aggregator if I wanted to. 

Were it to be added, something like this would be very useful to me...

```php
'stderr' => [ 
     'driver' => 'monolog',
     'handler' => StreamHandler::class,
     'with' => [ 'stream' => 'php://stderr', ], 
],
```

Apache is already sending every request log line out into the container's streams, so this would just add whatever you send to monolog out along with it.

The container is already setup for this out of the box, the apache log files are just symlinks to the container's standard io devices.

```bash
root@13c12ad51a79:/var/log/apache2# ls -la
total 8
drwxrwxrwt 2 www-data www-data 4096 Apr 24 08:44 .
drwxr-xr-x 1 root     root     4096 Apr 24 08:44 ..
lrwxrwxrwx 1 www-data www-data   11 Apr 24 08:44 access.log -> /dev/stdout
lrwxrwxrwx 1 www-data www-data   11 Apr 24 08:44 error.log -> /dev/stderr
lrwxrwxrwx 1 www-data www-data   11 Apr 24 08:44 other_vhosts_access.log -> /dev/stdout
```

I have zero idea why this isn't a standard practice with PHP/Apache like it seems to be with nearly any other setup.


Anyways, thanks again for this project and you're amazing support. I'm hoping for a continuation of the runaway success so far and that traction keeps coming in.

**Comment by simjanos-dev** [comment] 2024-04-30 16:48
I'll keep this open until I add the safety check for wordless phrases, and improving logging.

**Comment by simjanos-dev** [comment] 2024-05-03 13:05
I've changed the logging based on your suggestion. I replicated the error, and now it logs the more detailed error message to both the log file and to the docker webserver's terminal log. It will be in v0.12.

I've learned a bit about logging, I was not aware that I hid error messages partially.

**Comment by simjanos-dev** [comment] 2024-05-03 13:42
Added the protection against creating phrases without any words.

**Closed by simjanos-dev** 2024-05-03 13:42 UTC

**Comment by etherealite** [comment] 2024-05-08 19:13
Hey, thanks again for the super fast turn around on this.
